<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <DefineConstants Condition="'$(Zisk)' == 'true'">$(DefineConstants);ZISK</DefineConstants>
    <DefineConstants Condition="'$(Sp1)' == 'true'">$(DefineConstants);SP1</DefineConstants>
    <DefineConstants Condition="'$(OpenVm)' == 'true'">$(DefineConstants);OPENVM</DefineConstants>
  </PropertyGroup>

  <PropertyGroup>
    <Description>C# bindings for the zkVM Standards for Ethereum.</Description>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <PackageId>Nethermind.Zkvm.Abstractions</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://nethermind.io</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>zkvm;ethereum</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/nethermindeth/zkvm-abstractions</RepositoryUrl>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
