name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      feed:
        description: NuGet feed
        default: Staging
        type: choice
        options:
          - Staging
          - Production

jobs:
  publish:
    name: Publish
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      NUGET_HOST: ${{ github.event.inputs.feed == 'Staging' && 'https://int.nugettest.org' || 'https://www.nuget.org' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up .NET
        uses: actions/setup-dotnet@v6

      - name: NuGet login
        uses: nuget/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
          audience: ${{ env.NUGET_HOST }}
          token-service-url: ${{ env.NUGET_HOST }}/api/v2/token

      - name: Publish
        working-directory: src
        run: |
          dotnet pack -c release Nethermind.Zkvm.Abstractions.csproj -p:Zisk=true
          dotnet nuget push ./artifacts/package/release/*.nupkg \
            -k "${{ steps.login.outputs.NUGET_API_KEY }}" -s ${{ env.NUGET_HOST }}/api/v2/package
